# Generated by Django 4.2.8 on 2024-01-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('api_key', models.CharField(max_length=128)),
                ('check_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=128)),
                ('point_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('check_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=128)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=128)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.printer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
