# Generated by Django 4.2.8 on 2024-01-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_check_pdf_file_alter_check_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
