# Generated by Django 4.2.8 on 2024-01-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_check_check_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
