# Generated by Django 4.2.8 on 2024-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_check_check_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
