# Generated by Django 4.2.8 on 2024-01-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_check_address_check_name_check_phone_check_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='checks'),
        ),
    ]
